<?php
include 'conn.php';
if ($_SERVER["REQUEST_METHOD"] === 'GET')
{
    $email = $_GET["email"];

    $sql = "SELECT * FROM users WHERE email = '$email'";
    if ($conn->query($sql)->num_rows > 0) {
    
        /*send the autogenerated password to the email address of the shop*/
        /*Receipient*/
        $to = $email;

        $autoGenPassword = rand(10,99).date('Hm').rand(23,78);
        $maskedPassword = md5($autoGenPassword);

        /*Subject*/
        $subject = "Password Reset";

        /*Message*/

        $message = "Password request successful.
            <br>New Generated Password ".$autoGenPassword."
            <br>Please change your password any that you desire";

        /*html for the email*/
        $html = "
            <html>
            <head>
              <title>$subject</title>
            </head>
            <body>
              <h3>$subject</h3>
              <p>$message</p>
            </body>
            </html>
            ";
        /*To send HTML mail, the Content-type header must be set*/
        $headers[] = 'MIME-Version: 1.0';
        $headers[] = 'Content-type: text/html; charset=iso-8859-1';
        /*Additional headers
        @change ::-> please change the from header to the current domain name, or default emailing address for the website

        uncomment the mail line to permit emailing to happen*/
        // $headers[] = 'From: Password Reset <no-reply@bdt.net>';
        if(mail($to, $subject, $html, implode("\r\n", $headers))){
            $sql = "UPDATE users SET password = '$maskedPassword' WHERE email = '$email'";
            if ($conn->query($sql)) {
                $data["message"] = "Check your email";
                $data["status"] = true;
            }else{
                $data["message"] = "Reset Failed";
                $data["status"] = false;
            }
        }else{
            $data["message"] = "Email Sending Failed";
            $data["status"] = false;
        }
    }else{
        $data["message"] = "No Email Found";
        $data["status"] = false;
    }
}
else
{
    $data["message"] = "Invalid Request";
    $data["status"] = false;
}
echo json_encode($data);

